import { describe, it, expect, beforeAll, afterAll } from "vitest"
import Database from "better-sqlite3"
import { mkdtempSync, readFileSync, rmSync } from "node:fs"
import { join } from "node:path"
import { tmpdir } from "node:os"
import { writeFileSync } from "node:fs"
import { generateTypes } from "../src/cli/generate.js"

// ---------------------------------------------------------------------------
// Helpers
// ---------------------------------------------------------------------------

let tmpDir: string
let dbPath: string
let sqlite: Database.Database

beforeAll(() => {
    tmpDir = mkdtempSync(join(tmpdir(), "firelink-test-"))
    dbPath = join(tmpDir, "test.db")

    sqlite = new Database(dbPath)
    sqlite.exec(`
    CREATE TABLE users (
      id         INTEGER PRIMARY KEY AUTOINCREMENT,
      email      TEXT    NOT NULL,
      name       TEXT,
      score      REAL,
      is_active  INTEGER NOT NULL DEFAULT 1,
      created_at TEXT
    );
    CREATE TABLE posts (
      id      INTEGER PRIMARY KEY AUTOINCREMENT,
      title   TEXT    NOT NULL,
      body    TEXT,
      user_id INTEGER NOT NULL
    );
  `)
    sqlite.close()
})

afterAll(() => {
    rmSync(tmpDir, { recursive: true, force: true })
})

function writeConfig(overrides?: Record<string, unknown>): string {
    const config = {
        sql: { dialect: "sqlite", filename: dbPath },
        firestore: { projectId: "demo-test" },
        output: { typesFile: join(tmpDir, "firelink.types.ts") },
        ...overrides
    }
    const cfgPath = join(tmpDir, "firelink.config.json")
    writeFileSync(cfgPath, JSON.stringify(config))
    return cfgPath
}

function readGenerated(): string {
    return readFileSync(join(tmpDir, "firelink.types.ts"), "utf-8")
}

// ---------------------------------------------------------------------------
// Tests
// ---------------------------------------------------------------------------

describe("generateTypes (SQLite introspection)", () => {
    it("generates a file with a header comment", async () => {
        const cfgPath = writeConfig()
        await generateTypes(cfgPath)
        expect(readGenerated()).toContain("AUTO-GENERATED by firelink --schema")
    })

    it("generates an interface for each table", async () => {
        const cfgPath = writeConfig()
        await generateTypes(cfgPath)
        const output = readGenerated()
        expect(output).toContain("export interface UsersTable {")
        expect(output).toContain("export interface PostsTable {")
    })

    it("maps INTEGER to number", async () => {
        const cfgPath = writeConfig()
        await generateTypes(cfgPath)
        expect(readGenerated()).toContain("id: number")
        expect(readGenerated()).toContain("userId: number")
    })

    it("maps TEXT NOT NULL to string", async () => {
        const cfgPath = writeConfig()
        await generateTypes(cfgPath)
        expect(readGenerated()).toContain("email: string;")
        expect(readGenerated()).toContain("title: string;")
    })

    it("maps nullable TEXT to string | null", async () => {
        const cfgPath = writeConfig()
        await generateTypes(cfgPath)
        expect(readGenerated()).toContain("name: string | null;")
        expect(readGenerated()).toContain("body: string | null;")
    })

    it("maps REAL to number", async () => {
        const cfgPath = writeConfig()
        await generateTypes(cfgPath)
        expect(readGenerated()).toContain("score: number | null;")
    })

    it("converts snake_case column names to camelCase properties", async () => {
        const cfgPath = writeConfig()
        await generateTypes(cfgPath)
        const output = readGenerated()
        expect(output).toContain("isActive:")
        expect(output).toContain("createdAt:")
        expect(output).toContain("userId:")
        // snake_case originals should not appear as property names
        expect(output).not.toMatch(/  is_active:/)
        expect(output).not.toMatch(/  created_at:/)
        expect(output).not.toMatch(/  user_id:/)
    })

    it("generates a model class for each table", async () => {
        const cfgPath = writeConfig()
        await generateTypes(cfgPath)
        const output = readGenerated()
        expect(output).toContain("export class UsersModel {")
        expect(output).toContain("export class PostsModel {")
    })

    it("model class has add, set, update, delete methods", async () => {
        const cfgPath = writeConfig()
        await generateTypes(cfgPath)
        const output = readGenerated()
        expect(output).toContain("add(doc: Omit<UsersTable,")
        expect(output).toContain("set(id: string,")
        expect(output).toContain("update(id: string,")
        expect(output).toContain("delete(id: string)")
    })

    it("model class constructor accepts FirelinkInstance", async () => {
        const cfgPath = writeConfig()
        await generateTypes(cfgPath)
        expect(readGenerated()).toContain("import('firelink').FirelinkInstance")
    })

    it("model class hardcodes the collection name as the table name", async () => {
        const cfgPath = writeConfig()
        await generateTypes(cfgPath)
        const output = readGenerated()
        expect(output).toContain("client.collection<UsersTable>('users')")
        expect(output).toContain("client.collection<PostsTable>('posts')")
    })

    it("generates a FirelinkModels type map", async () => {
        const cfgPath = writeConfig()
        await generateTypes(cfgPath)
        const output = readGenerated()
        expect(output).toContain("export type FirelinkModels = {")
        expect(output).toContain("users: UsersTable")
        expect(output).toContain("posts: PostsTable")
    })

    it("respects custom firelinkPackage in config", async () => {
        const cfgPath = writeConfig({
            output: {
                typesFile: join(tmpDir, "firelink.types.ts"),
                firelinkPackage: "@myorg/firelink"
            }
        })
        await generateTypes(cfgPath)
        expect(readGenerated()).toContain("import('@myorg/firelink')")
    })

    it("throws when config file is missing", async () => {
        await expect(generateTypes("/nonexistent/path/firelink.config.json")).rejects.toThrow(/Could not read config/)
    })

    it("throws when sqlite filename is missing", async () => {
        const cfgPath = writeConfig({ sql: { dialect: "sqlite" } })
        await expect(generateTypes(cfgPath)).rejects.toThrow(/filename/)
    })
})
